# Generated by Django 2.0.6 on 2018-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sph', '0004_question_second_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(choices=[('1', '18-24'), ('2', '25-29'), ('3', '30-34'), ('4', '35-39'), ('5', '40-44'), ('6', '55-59'), ('7', '60-69'), ('8', '70+')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.CharField(choices=[('1', 'master'), ('2', 'bachelor'), ('3', 'high school'), ('4', 'unfinished tehcnical education'), ('5', 'finished middle education'), ('6', 'unfinished middle education')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='expenditures',
            field=models.CharField(choices=[('1', '2500'), ('2', '3000-4500'), ('3', '5000-7000'), ('4', '7500-10000'), ('5', '12000-15000'), ('6', '17000+')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='family_status',
            field=models.CharField(choices=[('married', 'MARRIED'), ('single', 'SINGLE'), ('widow', 'WIDOW'), ('divorced', 'DIVORCED')], default='married', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('another', 'ANOTHER')], default='male', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('1', 'businessman'), ('2', 'entrepreneur'), ('3', 'employed worker'), ('4', 'housewife'), ('5', 'student'), ('6', 'retired'), ('7', 'unemployed')], default='1', max_length=100),
        ),
    ]
