# Generated by Django 2.0.7 on 2018-07-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sph', '0005_auto_20180702_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='national_liberal',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='conservative_social',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='liberal_national',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='liberal_social',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ManyToManyField(to='sph.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='social_national',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='block',
            field=models.CharField(choices=[('Політичний', 'політичний'), ('Економічний', 'економічний'), ('Соціальний', 'соціальний')], default='Політичний', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='tag_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='type_block',
            field=models.CharField(choices=[('LC', 'liberal conservative'), ('CS', 'conservative social'), ('SN', 'social national')], default='LC', max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='conservative_national',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='liberal_conservative',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(choices=[('18-24', '18-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-54', '40-44'), ('55-59', '55-59'), ('60-69', '60-69'), ('70+', '70+')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(choices=[('Вища (магістр / спеціаліст)', 'master'), ('Вища (бакалавр)', 'bachelor'), ('Середня професійна освіта', 'high school'), ('Початкова професійна освіта', 'unfinished tehcnical education'), ('Середня (повна) загальна освіта', 'finished middle education'), ('Початкова загальна освіта', 'unfinished middle education')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='expenditures',
            field=models.CharField(choices=[('2,500 грн. або меньше', '2500'), ('3,000 - 4,500 грн.', '3000-4500'), ('5,000 - 7,000 грн.', '5000-7000'), ('7,500 - 10,000 грн.', '7500-10000'), ('12,000 - 15,000 грн.', '12000-15000'), ('17,000+ грн', '17000+')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_status',
            field=models.CharField(choices=[('Одружений(-а)', 'MARRIED'), ('Неодружений/Незаміжня', 'SINGLE'), ('Вдовець/Вдова', 'WIDOW'), ('Розлучений(-а)', 'DIVORCED')], default='married', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Чоловічий', 'ЧОЛОВІЧА'), ('Жіночий', 'ЖІНОЧА'), ('Інше', 'Інша')], default='чоловіча', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('Власник(-ця) бізнесу, юридична особа', 'businessman'), ('Фізична особа підприємець', 'entrepreneur'), ('Найманий працівник(-ця)', 'employed worker'), ('Домогосподар(-ка)', 'housewife'), ('Студент(-ка)', 'student'), ('Пенсіонер(-ка)', 'retired'), ('имчасово безробітній(-ня)', 'unemployed')], default='1', max_length=100),
        ),
    ]
